version: '3'

services:
  postgresdev:
        image: postgres
        ports:
         - "5432:5433"
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pgdev