create table RETAILERS (
  ID serial,
  ORG_NAME varchar(100) NOT NULL,
  PRIMARY_NAME VARCHAR(100) NOT NULL,
  SECONDARY_NAME VARCHAR(100) NOT NULL,
  LAT VARCHAR(100) NOT NULL,
  LON VARCHAR(100) NOT NULL
)